//! `tauri-build` driver. The app-command ACL manifest is derived from the
//! `generate_handler!` list in `src/invoke.rs` (see
//! `build_support/invoke_commands.rs`): every command gets an
//! autogenerated `allow-$cmd`/`deny-$cmd` permission, which the files in
//! `capabilities/` grant per window.
//!
//! tauri-build writes those permissions as one TOML per command into the
//! source-tree directory `permissions/autogenerated/` (gitignored), shared
//! by every profile, and never removes old files — it then globs the whole
//! directory. So the manifest cannot vary by profile: the
//! `#[cfg(debug_assertions)]` commands are always listed. That is safe
//! because release builds compile out both those commands and their grants
//! (`capabilities-dev/`, loaded only under `cfg(debug_assertions)` in
//! `setup.rs`), and `tests/capability_policy.rs` keeps debug grants out of
//! `capabilities/` (tauri-apps/tauri#13348: autogenerated files are pinned
//! to the source dir, not the per-target build dir).
//!
//! Files for commands no longer in `invoke.rs` are pruned here, or a
//! deleted command's permission would stay grantable forever. That cleanup
//! belongs in tauri-utils (`autogenerate_command_permissions`) and is
//! tracked upstream as tauri-apps/tauri#14320 (fix PR #14493 was approved
//! in review but closed unmerged). `prune_stale_permissions` mirrors that
//! fix and must be deleted once a tauri-build release performs it.

#[path = "build_support/invoke_commands.rs"]
mod invoke_commands;

const AUTOGENERATED_DIR: &str = "permissions/autogenerated";

/// Command names for `AppManifest::commands`. Leaked to `'static` because
/// the `tauri-build` API requires it; the build script exits right after.
fn app_commands() -> &'static [&'static str] {
    println!("cargo:rerun-if-changed=src/invoke.rs");
    println!("cargo:rerun-if-changed=build_support/invoke_commands.rs");
    let src = std::fs::read_to_string("src/invoke.rs")
        .unwrap_or_else(|e| panic!("read src/invoke.rs: {e}"));
    let commands = invoke_commands::parse(&src).unwrap_or_else(|e| panic!("{e}"));
    let names: Vec<&'static str> = commands
        .iter()
        .map(|c| &*Box::leak(c.name().to_owned().into_boxed_str()))
        .collect();
    Box::leak(names.into_boxed_slice())
}

/// Delete autogenerated permission files whose command is gone.
fn prune_stale_permissions(commands: &[&str]) {
    let Ok(entries) = std::fs::read_dir(AUTOGENERATED_DIR) else {
        return; // first build: tauri-build creates the directory
    };
    for entry in entries {
        let path = entry
            .unwrap_or_else(|e| panic!("read {AUTOGENERATED_DIR}: {e}"))
            .path();
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();
        let is_toml = path.extension().is_some_and(|e| e == "toml");
        if is_toml && !commands.contains(&stem) {
            std::fs::remove_file(&path)
                .unwrap_or_else(|e| panic!("remove stale {}: {e}", path.display()));
        }
    }
}

fn main() {
    // Make the compile-time target triple available at runtime for sidecar path resolution.
    println!(
        "cargo:rustc-env=REKINDLE_TARGET={}",
        std::env::var("TARGET").unwrap()
    );
    let commands = app_commands();
    prune_stale_permissions(commands);
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(commands)),
    )
    .unwrap_or_else(|e| panic!("tauri-build failed: {e:#}"));
}
