//! Proto3 wire types generated by `prost-build`.
//!
//! Generated from `proto/rekindle.proto` during `cargo build`.
//! All `bytes` fields are `Vec<u8>` (not `bytes::Bytes`) so secret
//! material can be zeroized after processing.

#[allow(clippy::trivially_copy_pass_by_ref, clippy::all)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/rekindle.v1.rs"));
}
pub use generated::*;
