//! Patch message types — structured code change payloads for inline diff
//! rendering, review, and application in communication channels and DMs.
//!
//! A patch is a first-class message content variant, not an attachment.
//! It encrypts and transports identically to text (MEK for channels,
//! Triple Ratchet for DMs). The receiving client recognizes the variant
//! and renders it as a syntax-highlighted, reviewable, applicable diff.

use serde::{Deserialize, Serialize};

/// Patch message content — carries a unified diff with structured metadata.
///
/// The `diff` field is the canonical representation (standard unified diff
/// format, compatible with `git apply`, `patch(1)`, and every diff tool).
/// The `files` field provides pre-parsed metadata so the renderer doesn't
/// need to re-parse the diff text for summary display.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PatchContent {
    /// Unified diff text — the canonical representation.
    /// Generated by `git2::Diff::print()` or `git diff`.
    pub diff: String,

    /// Per-file metadata for summary rendering without re-parsing.
    pub files: Vec<PatchFileMeta>,

    /// Human-readable description of the change (optional).
    /// Rendered above the diff as context.
    pub description: Option<String>,

    /// The base commit hash this patch was generated against.
    /// Used for conflict detection: if the recipient's HEAD differs
    /// from this ref, the patch may not apply cleanly.
    pub base_ref: Option<String>,

    /// The branch name the patch was generated from (informational).
    pub source_branch: Option<String>,
}

/// Per-file metadata within a patch.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PatchFileMeta {
    /// Relative path of the file.
    pub path: String,

    /// What happened to this file.
    pub status: PatchFileStatus,

    /// Number of lines added.
    pub additions: u32,

    /// Number of lines removed.
    pub deletions: u32,

    /// Original path before rename (only set for `Renamed`).
    pub old_path: Option<String>,
}

/// File status within a patch.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PatchFileStatus {
    /// New file created.
    Added,
    /// Existing file modified.
    Modified,
    /// File deleted.
    Deleted,
    /// File renamed (old_path → path).
    Renamed,
}

impl PatchContent {
    /// Total additions across all files.
    pub fn total_additions(&self) -> u32 {
        self.files.iter().map(|f| f.additions).sum()
    }

    /// Total deletions across all files.
    pub fn total_deletions(&self) -> u32 {
        self.files.iter().map(|f| f.deletions).sum()
    }

    /// Total files affected.
    pub fn file_count(&self) -> usize {
        self.files.len()
    }

    /// Compact summary string: "3 files (+42/-17)"
    pub fn summary(&self) -> String {
        let fc = self.file_count();
        let file_word = if fc == 1 { "file" } else { "files" };
        format!("{fc} {file_word} (+{}/-{})", self.total_additions(), self.total_deletions())
    }
}

impl std::fmt::Display for PatchFileStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Added => write!(f, "added"),
            Self::Modified => write!(f, "modified"),
            Self::Deleted => write!(f, "deleted"),
            Self::Renamed => write!(f, "renamed"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn patch_content_roundtrip() {
        let patch = PatchContent {
            diff: "--- a/foo.rs\n+++ b/foo.rs\n@@ -1 +1 @@\n-old\n+new\n".into(),
            files: vec![PatchFileMeta {
                path: "foo.rs".into(),
                status: PatchFileStatus::Modified,
                additions: 1,
                deletions: 1,
                old_path: None,
            }],
            description: Some("Fix the thing".into()),
            base_ref: Some("abc123".into()),
            source_branch: Some("fix/the-thing".into()),
        };
        let json = serde_json::to_string(&patch).unwrap();
        let back: PatchContent = serde_json::from_str(&json).unwrap();
        assert_eq!(patch, back);
    }

    #[test]
    fn summary_formatting() {
        let patch = PatchContent {
            diff: String::new(),
            files: vec![
                PatchFileMeta { path: "a.rs".into(), status: PatchFileStatus::Modified, additions: 10, deletions: 5, old_path: None },
                PatchFileMeta { path: "b.rs".into(), status: PatchFileStatus::Added, additions: 32, deletions: 0, old_path: None },
                PatchFileMeta { path: "c.rs".into(), status: PatchFileStatus::Deleted, additions: 0, deletions: 12, old_path: None },
            ],
            description: None,
            base_ref: None,
            source_branch: None,
        };
        assert_eq!(patch.summary(), "3 files (+42/-17)");
    }

    #[test]
    fn single_file_summary() {
        let patch = PatchContent {
            diff: String::new(),
            files: vec![PatchFileMeta {
                path: "main.rs".into(), status: PatchFileStatus::Modified,
                additions: 1, deletions: 1, old_path: None,
            }],
            description: None, base_ref: None, source_branch: None,
        };
        assert_eq!(patch.summary(), "1 file (+1/-1)");
    }
}
