//! Phase 14 — group call state (architecture §10.10, W12.9 + W13.13).
//!
//! Pre-Phase-14 this lived in `src-tauri/services/group_calls.rs` as a
//! pub struct on `AppState.group_calls: Mutex<HashMap<String, GroupCallState>>`.
//! Moved into the crate so the signaling logic can be parameterized
//! over `GroupCallRegistry` (a trait in `signaling.rs`) rather than
//! reaching into `AppState`.

use std::collections::HashSet;

use x25519_dalek::StaticSecret;

/// Status of an in-flight group call.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GroupCallStatus {
    /// We initiated; waiting on participants to accept.
    Outgoing,
    /// We received an invite; awaiting user accept/decline.
    Incoming,
    /// At least one participant accepted; call is in progress.
    Active,
    /// Call ended (will be removed from registry on next prune).
    Ended,
}

/// One in-flight group call. The shared `call_key` is generated by the
/// initiator and distributed to each participant via per-recipient
/// X25519-wrapped envelopes (see [`crate::group::wrap_call_key`]).
///
/// `our_x25519_secret` is held in [`StaticSecret`] so it's zeroized on
/// drop (group DM key wrap uses StaticSecret rather than EphemeralSecret
/// because the secret must persist across the request/reply round-trip).
pub struct GroupCallState {
    pub call_id: String,
    /// Initiator's Ed25519 public key, hex-encoded.
    pub initiator_pubkey: String,
    /// Call kind: 0 = audio, 1 = video. Matches [`crate::CallKind`] wire form.
    pub kind: u8,
    /// All participants invited (hex Ed25519 public keys).
    pub participants: Vec<String>,
    /// Participants who have replied with `GroupCallAccept`.
    pub accepted: HashSet<String>,
    /// Our X25519 secret for this call. Zeroized when the struct drops.
    pub our_x25519_secret: Option<StaticSecret>,
    /// Shared 32-byte symmetric key used by `rekindle-voice` for frame
    /// AEAD. `None` for the initiator until the first `GroupCallAccept`
    /// arrives (call_key is generated at start_group_call time, then
    /// stored here).
    pub call_key: Option<[u8; 32]>,
    pub status: GroupCallStatus,
}

impl std::fmt::Debug for GroupCallState {
    /// Custom Debug hides the call_key and X25519 secret so logs/dumps
    /// never leak key material.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GroupCallState")
            .field("call_id", &self.call_id)
            .field("initiator_pubkey", &self.initiator_pubkey)
            .field("kind", &self.kind)
            .field("participants_count", &self.participants.len())
            .field("accepted_count", &self.accepted.len())
            .field("has_secret", &self.our_x25519_secret.is_some())
            .field("has_call_key", &self.call_key.is_some())
            .field("status", &self.status)
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn debug_redacts_secret_and_key() {
        let state = GroupCallState {
            call_id: "abc".into(),
            initiator_pubkey: "deadbeef".into(),
            kind: 0,
            participants: vec!["p1".into(), "p2".into()],
            accepted: HashSet::new(),
            our_x25519_secret: Some(StaticSecret::random_from_rng(rand::rngs::OsRng)),
            call_key: Some([0xAB; 32]),
            status: GroupCallStatus::Outgoing,
        };
        let dbg = format!("{state:?}");
        // Must NOT contain the actual key bytes or any hex pattern that
        // would suggest a 32-byte key leaked through.
        assert!(!dbg.contains("AB"));
        assert!(dbg.contains("has_call_key: true"));
        assert!(dbg.contains("has_secret: true"));
        assert!(dbg.contains("participants_count: 2"));
    }

    #[test]
    fn status_variants_present() {
        let _ = GroupCallStatus::Outgoing;
        let _ = GroupCallStatus::Incoming;
        let _ = GroupCallStatus::Active;
        let _ = GroupCallStatus::Ended;
    }
}
