//! Tests for the join-stage state machine.

use super::*;

#[test]
fn governance_snapshot_struct_fields_accessible() {
    // Smoke check: GovernanceSnapshot can be constructed + read.
    let snap = GovernanceSnapshot {
        all_entries: Vec::new(),
        gov_state: GovernanceState::default(),
        name: "t".into(),
        description: None,
        overflow_keys: Vec::new(),
    };
    assert_eq!(snap.name, "t");
    assert!(snap.all_entries.is_empty());
    assert!(snap.overflow_keys.is_empty());
}

/// The retry mechanism from architecture §6.2 step 9.
///
/// Uses `mockall` expectations rather than a hand-written double:
/// this is the case its docs single out — "you are testing a retry
/// mechanism and want to make sure it retries according to the
/// configured policy". The 66-method trait is generated by
/// `#[automock]`, so only the four methods this path touches need
/// expectations.
#[tokio::test]
async fn slot_claim_steps_over_contended_subkeys() {
    use crate::deps::MockGovernanceRuntimeDeps;

    let me = PseudonymKey([7u8; 32]);
    let signing = SigningKey::from_bytes(&[3u8; 32]);

    // What a successful read-back looks like: our own presence.
    let mine = MemberPresence {
        pseudonym_key: me.clone(),
        ..Default::default()
    };
    let mine_bytes = serde_json::to_vec(&mine).unwrap();

    let mut deps = MockGovernanceRuntimeDeps::new();
    deps.expect_open_dht_record().returning(|_, _| Ok(()));
    // Every subkey free at inspect time — the contention only shows
    // up at write time, which is the race this exercises.
    deps.expect_inspect_dht_record_present_subkeys()
        .returning(|_| Ok(vec![]));
    deps.expect_format_writer_keypair()
        .returning(|_, _| "kp".to_string());

    // Subkeys 0 and 1 are taken by other joiners between our inspect
    // and our write; 2 lands. `Some(_)` is veilid's compare-and-swap
    // signal — the value the network already held.
    let mut attempt = 0;
    deps.expect_set_dht_value()
        .times(3)
        .returning(move |_, subkey, _, _| {
            attempt += 1;
            assert_eq!(subkey, attempt - 1, "must step to the next free subkey");
            if attempt < 3 {
                Ok(Some(vec![0xAA]))
            } else {
                Ok(None)
            }
        });
    deps.expect_get_dht_value()
        .returning(move |_, _, _| Ok(Some(mine_bytes.clone())));

    let gov_state = GovernanceState::default();
    let ctx = SlotClaimCtx {
        community_id: "c1",
        invite_registry_key: "reg",
        inviter_pseudonym: None,
        my_pseudo: &me,
        pseudonym_signing: &signing,
        gov_state: &gov_state,
        join_status_label: "online",
        display_name: None,
    };

    let claimed = claim_registry_slot(&deps, &hex::encode([1u8; 32]), ctx)
        .await
        .expect("claim must succeed after stepping over two contended slots");
    assert_eq!(
        claimed.local_subkey, 2,
        "should land on the first subkey that was not taken from under us"
    );
}

/// Contention must not retry forever: five attempts, then give up on
/// the segment rather than spinning against a hot registry.
#[tokio::test]
async fn slot_claim_gives_up_after_the_attempt_cap() {
    use crate::deps::MockGovernanceRuntimeDeps;

    let me = PseudonymKey([7u8; 32]);
    let signing = SigningKey::from_bytes(&[3u8; 32]);

    let mut deps = MockGovernanceRuntimeDeps::new();
    deps.expect_open_dht_record().returning(|_, _| Ok(()));
    deps.expect_inspect_dht_record_present_subkeys()
        .returning(|_| Ok(vec![]));
    deps.expect_format_writer_keypair()
        .returning(|_, _| "kp".to_string());
    // Every write loses the race.
    deps.expect_set_dht_value()
        .times(MAX_SLOT_CLAIM_ATTEMPTS as usize)
        .returning(|_, _, _, _| Ok(Some(vec![0xAA])));

    let gov_state = GovernanceState::default();
    let ctx = SlotClaimCtx {
        community_id: "c1",
        invite_registry_key: "reg",
        inviter_pseudonym: None,
        my_pseudo: &me,
        pseudonym_signing: &signing,
        gov_state: &gov_state,
        join_status_label: "online",
        display_name: None,
    };

    let result = claim_registry_slot(&deps, &hex::encode([1u8; 32]), ctx).await;
    assert!(
        result.is_err(),
        "after {MAX_SLOT_CLAIM_ATTEMPTS} contended attempts the claim must stop, \
             not spin against a registry every other joiner is also hammering"
    );
}

#[test]
fn claimed_slot_carries_keypair_string() {
    let slot = ClaimedSlot {
        registry_key: "rk".into(),
        segment_index: 0,
        local_subkey: 5,
        slot_keypair_str: "kp".into(),
        occupied_subkeys: vec![],
        self_presence: MemberPresence::default(),
    };
    assert_eq!(slot.registry_key, "rk");
    assert_eq!(slot.local_subkey, 5);
}
