//! DM MEK derivation and forward-secure ratchet chain.
//!
//! Used for **group DMs only**. 1:1 DMs use Triple Ratchet via
//! `DmDeps::ratchet_encrypt` / `ratchet_decrypt`.
//!
//! Group DM MEK is a random 32-byte key generated by the initiator and
//! wrapped per-recipient via ECDH. The chain ratchets forward every 100
//! messages or 24 hours, whichever comes first.
//!
//! Ratchet derivation:
//! ```text
//! mek_n+1 = HKDF-SHA256(mek_n, salt: empty, info: "rekindle-dm-ratchet-v1")
//! ```
//!
//! The chain lazy-materializes generations on demand and caches them
//! for O(1) subsequent lookups.

use aws_lc_rs::hkdf::{Salt, HKDF_SHA256};
use zeroize::Zeroize;

use crate::dm::error::DmError;

pub const MEK_LEN: usize = 32;

/// Forward-secure ratchet thresholds.
pub const DM_RATCHET_MESSAGE_INTERVAL: u64 = 100;
pub const DM_RATCHET_TIME_INTERVAL_SECS: i64 = 86_400; // 24h

/// 32-byte symmetric MEK. Zeroized on drop.
#[derive(Clone, Zeroize)]
pub struct DmMek(pub [u8; MEK_LEN]);

impl DmMek {
    pub fn as_bytes(&self) -> &[u8; MEK_LEN] {
        &self.0
    }
}

impl Drop for DmMek {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

impl std::fmt::Debug for DmMek {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DmMek").field("len", &MEK_LEN).finish()
    }
}

// ── HKDF helpers ────────────────────────────────────────────────────

struct Len32;
impl aws_lc_rs::hkdf::KeyType for Len32 {
    fn len(&self) -> usize {
        32
    }
}

fn hkdf_expand(ikm: &[u8], salt_bytes: &[u8], info: &[u8]) -> Result<[u8; 32], DmError> {
    let salt = Salt::new(HKDF_SHA256, salt_bytes);
    let prk = salt.extract(ikm);
    let info_arr = [info];
    let okm = prk
        .expand(&info_arr, Len32)
        .map_err(|_| DmError::EncryptFailed("hkdf expand".into()))?;
    let mut out = [0u8; 32];
    okm.fill(&mut out)
        .map_err(|_| DmError::EncryptFailed("hkdf fill".into()))?;
    Ok(out)
}

// ── Deterministic 2-party MEK derivation ────────────────────────────

/// Derive the deterministic 2-party DM MEK from X25519 identity keys.
///
/// Used during group DM setup for MEK wrapping ECDH, NOT for 1:1 DM
/// encryption (1:1 uses Triple Ratchet). Both peers produce the same
/// key from their identity material with no round-trip.
///
/// ```text
/// ikm  = X25519(my_secret, their_public)
/// salt = BLAKE3(sorted(my_ed_pub || their_ed_pub))
/// mek  = HKDF-SHA256(ikm, salt, "rekindle-dm-mek-v1", 32)
/// ```
pub fn derive_dm_mek(
    my_x25519_seed: &[u8; 32],
    their_x25519_pub: &[u8; 32],
    my_ed25519_pub: &[u8; 32],
    their_ed25519_pub: &[u8; 32],
) -> Result<DmMek, DmError> {
    // X25519 ECDH shared secret
    let our_key = rekindle_ratchet::crypto::dh::reusable_from_seed(my_x25519_seed)
        .map_err(|e| DmError::EncryptFailed(format!("x25519 from seed: {e}")))?;
    let shared = rekindle_ratchet::crypto::dh::ratchet_agree(&our_key, their_x25519_pub)
        .map_err(|e| DmError::EncryptFailed(format!("x25519 ecdh: {e}")))?;

    // Commutative salt: BLAKE3(sorted(my_pub || their_pub))
    let salt_hash = if my_ed25519_pub <= their_ed25519_pub {
        let mut input = [0u8; 64];
        input[..32].copy_from_slice(my_ed25519_pub);
        input[32..].copy_from_slice(their_ed25519_pub);
        blake3::hash(&input)
    } else {
        let mut input = [0u8; 64];
        input[..32].copy_from_slice(their_ed25519_pub);
        input[32..].copy_from_slice(my_ed25519_pub);
        blake3::hash(&input)
    };

    let mek_bytes = hkdf_expand(shared.as_ref(), salt_hash.as_bytes(), b"rekindle-dm-mek-v1")?;

    tracing::trace!(
        my_pub_short = hex::encode(&my_ed25519_pub[..4]),
        their_pub_short = hex::encode(&their_ed25519_pub[..4]),
        "derive_dm_mek: deterministic MEK derived"
    );

    Ok(DmMek(mek_bytes))
}

// ── Forward-secure ratchet ──────────────────────────────────────────

/// Derive next-generation MEK from the previous.
pub fn ratchet_dm_mek(prev: &DmMek) -> Result<DmMek, DmError> {
    let next = hkdf_expand(prev.as_bytes(), &[], b"rekindle-dm-ratchet-v1")?;
    Ok(DmMek(next))
}

// ── Lazily-materialized chain ───────────────────────────────────────

/// Forward-secure MEK chain. Each generation is derived from the
/// previous via `ratchet_dm_mek`. Generations are materialized lazily
/// and cached for O(1) subsequent lookups.
///
/// Used by group DM sender (current outbound generation) and receiver
/// (observed inbound generation with forward-locking).
#[derive(Clone)]
pub struct DmMekChain {
    cache: Vec<DmMek>,
    current_gen: u64,
}

impl DmMekChain {
    /// Build a fresh chain rooted at the genesis MEK (generation 0).
    pub fn new(genesis: DmMek) -> Self {
        Self {
            cache: vec![genesis],
            current_gen: 0,
        }
    }

    /// Restore a chain whose tip is already advanced to `current_gen`.
    /// Used when restoring from SQLite — the persisted `mek_generation`
    /// column is the chain's tip.
    pub fn restore(genesis: DmMek, current_gen: u64) -> Result<Self, DmError> {
        let mut chain = Self::new(genesis);
        if current_gen > 0 {
            chain.materialize_through(current_gen)?;
            chain.current_gen = current_gen;
        }
        tracing::trace!(current_gen, "DmMekChain::restore: chain restored");
        Ok(chain)
    }

    /// Get the MEK for `gen`, deriving any missing generations.
    pub fn for_generation(&mut self, gen: u64) -> Result<&DmMek, DmError> {
        self.materialize_through(gen)?;
        self.cache
            .get(usize::try_from(gen).unwrap_or(usize::MAX))
            .ok_or_else(|| DmError::MekChainUnavailable(format!("gen {gen}")))
    }

    /// Current outbound (writer) generation and its MEK bytes.
    pub fn current(&mut self) -> Result<([u8; 32], u64), DmError> {
        let gen = self.current_gen;
        let mek = self.for_generation(gen)?;
        Ok((*mek.as_bytes(), gen))
    }

    /// Advance the chain to the next generation. Returns new gen.
    pub fn advance(&mut self) -> Result<u64, DmError> {
        let next = self.current_gen.saturating_add(1);
        self.materialize_through(next)?;
        self.current_gen = next;
        tracing::debug!(generation = next, "DmMekChain::advance: ratcheted forward");
        Ok(next)
    }

    /// Forward-lock: set our writer generation to max(ours, observed).
    /// Returns MEK bytes for the observed generation.
    ///
    /// Called by the receiver when an inbound message carries a generation
    /// higher than our current. Ensures our next outbound write never
    /// uses a lower generation (monotonic convergence).
    pub fn observed_and_lookup(&mut self, observed: u64) -> Result<[u8; 32], DmError> {
        self.materialize_through(observed)?;
        if observed > self.current_gen {
            tracing::debug!(
                old_gen = self.current_gen,
                new_gen = observed,
                "DmMekChain: forward-locked to observed generation"
            );
            self.current_gen = observed;
        }
        self.cache
            .get(usize::try_from(observed).unwrap_or(usize::MAX))
            .map(|m| *m.as_bytes())
            .ok_or_else(|| DmError::MekChainUnavailable(format!("gen {observed}")))
    }

    fn materialize_through(&mut self, gen: u64) -> Result<(), DmError> {
        let target = usize::try_from(gen).unwrap_or(usize::MAX);
        while self.cache.len() <= target {
            let prev = self.cache.last().expect("genesis always present");
            self.cache.push(ratchet_dm_mek(prev)?);
        }
        Ok(())
    }
}

impl std::fmt::Debug for DmMekChain {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DmMekChain")
            .field("current_gen", &self.current_gen)
            .field("cached_through", &self.cache.len())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_mek() -> DmMek {
        DmMek([0xab; 32])
    }

    #[test]
    fn ratchet_advances() {
        let m0 = test_mek();
        let m1 = ratchet_dm_mek(&m0).unwrap();
        assert_ne!(m0.as_bytes(), m1.as_bytes());
        let m2 = ratchet_dm_mek(&m1).unwrap();
        assert_ne!(m1.as_bytes(), m2.as_bytes());
    }

    #[test]
    fn chain_lazy_materialize() {
        let genesis = test_mek();
        let expected = ratchet_dm_mek(&ratchet_dm_mek(&genesis).unwrap()).unwrap();
        let mut chain = DmMekChain::new(genesis);
        let got = chain.for_generation(2).unwrap();
        assert_eq!(got.as_bytes(), expected.as_bytes());
    }

    #[test]
    fn chain_observed_locks_forward() {
        let mut chain = DmMekChain::new(test_mek());
        chain.observed_and_lookup(5).unwrap();
        assert_eq!(chain.current().unwrap().1, 5);
        // Lower observation does NOT roll back
        chain.observed_and_lookup(2).unwrap();
        assert_eq!(chain.current().unwrap().1, 5);
    }

    #[test]
    fn chain_advance_monotonic() {
        let mut chain = DmMekChain::new(test_mek());
        assert_eq!(chain.advance().unwrap(), 1);
        assert_eq!(chain.advance().unwrap(), 2);
        assert_eq!(chain.current().unwrap().1, 2);
    }

    #[test]
    fn chain_restore_resumes() {
        let genesis = test_mek();
        let restored = DmMekChain::restore(genesis.clone(), 3).unwrap();
        let mut fresh = DmMekChain::new(genesis);
        fresh.observed_and_lookup(3).unwrap();
        assert_eq!(restored.current_gen, fresh.current_gen);
    }
}
