//! Tauri IPC command registration.
//!
//! Holds the full `generate_handler!` command list, split out of `lib.rs` to
//! keep the entrypoint thin.

use crate::commands;

/// Build the invoke handler with every registered frontend → Rust command.
pub fn handler() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // auth
        commands::auth::create_identity,
        commands::auth::login,
        commands::auth::get_identity,
        commands::auth::logout,
        commands::auth::list_identities,
        commands::auth::delete_identity,
        #[cfg(debug_assertions)]
        commands::auth::pqxdh_bundle_info,
        commands::auth::audit_verify,
        commands::auth::audit_export,
        commands::auth::lifecycle_current,
        commands::auth::friendship_scan_now,
        commands::auth::dev_disable_watch,
        commands::event::event_resume,
        // chat
        commands::chat::prepare_chat_session,
        commands::chat::send_message,
        commands::chat::send_typing,
        commands::chat::get_message_history,
        commands::chat::mark_read,
        // friends
        commands::friends::add_friend,
        commands::friends::remove_friend,
        commands::friends::accept_request,
        commands::friends::get_friends,
        commands::friends::reject_request,
        commands::friends::get_pending_requests,
        commands::friends::create_friend_group,
        commands::friends::rename_friend_group,
        commands::friends::move_friend_to_group,
        commands::friends::generate_invite,
        commands::friends::add_friend_from_invite,
        commands::friends::block_user,
        commands::friends::unblock_user,
        commands::friends::get_blocked_users,
        commands::friends::cancel_request,
        commands::friends::cancel_invite,
        commands::friends::get_outgoing_invites,
        commands::friends::emit_friends_presence,
        commands::friends::reset_signal_session,
        commands::friends::accept_session_reset,
        commands::friends::decline_session_reset,
        // community
        commands::community::create_community,
        commands::community::join_community,
        commands::community::create_channel,
        commands::community::create_category,
        commands::community::delete_category,
        commands::community::rename_category,
        commands::community::move_channel,
        commands::community::reorder_categories,
        commands::community::create_community_invite,
        commands::community::revoke_community_invite,
        commands::community::list_community_invites,
        commands::community::send_channel_message,
        commands::community::edit_channel_message,
        commands::community::delete_channel_message,
        commands::community::get_channel_messages,
        commands::community::get_communities,
        commands::community::get_community_details,
        commands::community::get_community_members,
        commands::community::remove_community_member,
        commands::community::get_roles,
        commands::community::create_role,
        commands::community::edit_role,
        commands::community::delete_role,
        commands::community::assign_role,
        commands::community::unassign_role,
        commands::community::self_assign_role,
        commands::community::self_unassign_role,
        commands::community::timeout_member,
        commands::community::remove_timeout,
        commands::community::set_channel_overwrite,
        commands::community::delete_channel_overwrite,
        commands::community::set_slowmode,
        commands::community::admin_delete_channel_message,
        commands::community::bulk_delete_channel_messages,
        commands::community::forward_channel_message,
        commands::community::upload_attachment,
        commands::community::download_attachment,
        commands::community::pin_attachment,
        commands::community::send_voice_message,
        commands::community::expand_community_segment,
        commands::community::leave_community,
        commands::community::delete_channel,
        commands::community::rename_channel,
        commands::community::update_community_info,
        commands::community::ban_member,
        commands::community::unban_member,
        commands::community::get_ban_list,
        commands::community::rotate_mek,
        commands::community::set_channel_notification_level,
        commands::community::set_community_default_notification_level,
        commands::community::set_notification_sound,
        commands::community::get_notification_sound,
        commands::community::set_do_not_disturb,
        commands::community::get_do_not_disturb,
        commands::community::get_community_default_notification_level,
        commands::community::set_quiet_hours,
        commands::community::get_quiet_hours,
        commands::community::add_reaction,
        commands::community::remove_reaction,
        commands::community::pin_message,
        commands::community::unpin_message,
        commands::community::get_channel_pins,
        commands::community::get_audit_log,
        commands::community::get_community_analytics,
        commands::community::fetch_link_preview,
        commands::community::get_link_previews_enabled,
        commands::community::set_link_previews_enabled,
        commands::community::run_background_sync,
        commands::community::list_automod_rules,
        commands::community::set_automod_rule,
        commands::community::delete_automod_rule,
        commands::community::get_onboarding_config,
        commands::community::set_onboarding_config,
        commands::community::get_welcome_screen,
        commands::community::set_welcome_screen,
        commands::community::submit_onboarding_answers,
        commands::community::mark_onboarding_complete,
        commands::community::get_community_policy,
        commands::community::set_community_policy,
        commands::community::set_community_avatar,
        commands::community::set_community_banner,
        commands::community::get_community_avatar_data_url,
        commands::community::debug_gossip_state,
        commands::community::send_channel_typing,
        commands::community::set_active_channel,
        commands::community::set_presence_policy,
        commands::community::get_presence_policy,
        commands::community::update_community_presence,
        commands::community::update_community_profile,
        commands::community::get_older_channel_messages,
        commands::community::set_channel_topic,
        commands::community::set_channel_forum_tags,
        commands::community::reorder_channels,
        commands::community::create_poll,
        commands::community::vote_poll,
        commands::community::close_poll,
        commands::community::get_poll_results,
        commands::community::upload_emoji,
        commands::community::upload_sticker,
        commands::community::upload_soundboard_sound,
        commands::community::play_soundboard,
        commands::community::derive_video_stream_id,
        commands::community::default_media_capabilities,
        commands::community::send_video_frame,
        commands::community::send_video_frame_ack,
        commands::community::send_video_keyframe_request,
        commands::community::send_video_bandwidth_estimate,
        commands::community::notify_video_topology_change,
        commands::community::register_community_video_channel,
        commands::community::unregister_community_video_channel,
        commands::community::report_local_video_capabilities,
        commands::community::report_video_decoder_status,
        commands::community::report_video_encoder_status,
        commands::community::delete_emoji,
        commands::community::list_expressions,
        // community threads
        commands::community::create_thread,
        commands::community::get_active_threads,
        commands::community::get_channel_threads,
        commands::community::send_thread_message,
        commands::community::get_thread_messages,
        commands::community::archive_thread,
        commands::community::unarchive_thread,
        // community events
        commands::community::create_event,
        commands::community::edit_event,
        commands::community::delete_event,
        commands::community::cancel_event,
        commands::community::rsvp_event,
        commands::community::set_event_rsvp,
        commands::community::list_event_attendees,
        commands::community::get_events,
        // community game servers
        commands::community::add_game_server,
        commands::community::remove_game_server,
        commands::community::get_game_servers,
        // community unread tracking
        commands::community::mark_channel_read,
        commands::community::get_unread_counts,
        // voice
        commands::voice::join_voice_channel,
        commands::voice::leave_voice,
        commands::voice::request_to_speak,
        commands::voice::get_stage_hand_raises,
        commands::voice::respond_to_speak_request,
        commands::voice::set_mute,
        commands::voice::set_deafen,
        commands::voice::list_audio_devices,
        commands::voice::set_audio_devices,
        commands::voice::set_voice_mode,
        commands::voice::server_mute_member,
        commands::voice::server_deafen_member,
        // direct calls (Plan §Failure 5)
        commands::calls::start_dm_call,
        commands::calls::accept_dm_call,
        commands::calls::decline_dm_call,
        commands::calls::end_dm_call,
        commands::calls::send_call_media_state,
        commands::calls::send_call_reaction,
        commands::calls::mute_caller_temp,
        commands::calls::start_group_call,
        commands::calls::accept_group_call,
        commands::calls::decline_group_call,
        commands::calls::end_group_call,
        commands::calls::get_missed_calls,
        commands::calls::dm_peer_video_decode_codecs,
        // status
        commands::status::set_status,
        commands::status::set_nickname,
        commands::status::set_avatar,
        commands::status::get_avatar,
        commands::status::set_status_message,
        // game
        commands::game::get_game_status,
        commands::game::get_game_name,
        commands::game::launch_game_to_server,
        // strand relay
        commands::relay::volunteer_relay,
        commands::relay::revoke_relay,
        commands::relay::list_received_relay_offers,
        commands::relay::list_volunteered_relay_friends,
        // direct messages
        commands::dm::list_dms,
        commands::dm::start_dm,
        commands::dm::accept_dm_invite,
        commands::dm::decline_dm_invite,
        commands::dm::send_dm_message,
        commands::dm::get_dm_messages,
        commands::dm::send_dm_video_frame,
        commands::dm::register_dm_video_channel,
        commands::dm::unregister_dm_video_channel,
        // search (architecture §23)
        commands::search::search_messages,
        // cross-device sync (architecture §28.4)
        commands::sync::ensure_personal_sync_record,
        commands::sync::start_pairing_session,
        commands::sync::generate_pairing_qr_svg,
        commands::sync::accept_pairing_code,
        commands::sync::read_sync_manifest,
        commands::sync::write_sync_manifest,
        commands::sync::read_sync_read_state,
        commands::sync::write_sync_read_state,
        commands::sync::read_sync_preferences,
        commands::sync::write_sync_preferences,
        commands::sync::read_paired_devices,
        commands::sync::write_paired_devices,
        // mobile push relay
        commands::push_relay::register_with_push_relay,
        commands::push_relay::unregister_with_push_relay,
        commands::push_relay::list_push_relay_registrations,
        // settings
        commands::settings::get_preferences,
        commands::settings::set_preferences,
        commands::settings::check_for_updates,
        // windows
        commands::window::show_buddy_list,
        commands::window::open_chat_window,
        commands::window::open_dm_window,
        commands::window::open_settings_window,
        commands::window::open_community_window,
        commands::window::open_profile_window,
        commands::window::open_call_window,
        commands::window::get_network_status,
        // Phase 2 — dev-only vault diagnostics (compiled out of release).
        #[cfg(debug_assertions)]
        commands::vault::vault_diagnostics,
    ]
}
